### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by Helixable** [1s3k3b/krunker.io.js#1]
Can you make a CDN for this?

**Comment by 1s3k3b** [comment]
Hello, I've tried, but I falied because I used simple Browserify, and it didn't allow the ws module. I can try again sometime. Kinda new to CDNs though. I'll keep you updated in this issue.

**Comment by Helixable** [comment]
You don't need that module. 
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

**Comment by 1s3k3b** [comment]
I'm aware, I just found it a lot of time to rewrite all the code with browser WebSockets.

**Comment by Helixable** [comment]
Oh ok.

**Comment by 1s3k3b** [comment]
@Hoodgail is making a CDN, I'll keep this issue open until it's done.

**Comment by Helixable** [comment]
Got it. Thanks for the update.

**Comment by 1s3k3b** [comment]
https://1s3k3b.github.io/krunkerjs/cdn/krunkerio.js
