### ISSUE TITLE
Bot Player

### ISSUE THREAD

**Issue by Helixable** [1s3k3b/krunker.io.js#13]
I think I found a way to intercept Krunker.io sockets and maybe even control them. This could be used to make automated user accounts. 
If I end up figuring out the technical parts of this, do you think it would be ok if I added it to your package? (As a PR of course)

**Comment by Jytesh** [comment]
> I think I found a way to intercept Krunker.io sockets and maybe even control them. This could be used to make automated user accounts.
> If I end up figuring out the technical parts of this, do you think it would be ok if I added it to your package? (As a PR of course)

It would be better if you discussed the code privately, if this gets leaked hackers will be all over it.

**Comment by 1s3k3b** [comment]
agreed, it's out of the scope of the library.
