### ISSUE TITLE
Some minor bugs and Social section not working

### ISSUE THREAD

**Issue by Xyrrm** [1s3k3b/krunker.io.js#18]
![profile-image](https://user-images.githubusercontent.com/61253269/77092775-15ee1b80-69d8-11ea-9210-13b51ac3b337.png)
![Screen Shot 2020-03-19 at 11 50 32 AM](https://user-images.githubusercontent.com/61253269/77092778-1686b200-69d8-11ea-8619-a3764f40cb12.png)

- Melee kills throws undefined (even though I have 320)
- Kills per game and Accuracy is incorrectly calculated
- Update calculation for W/L ratio
- Entire social tab doesn't work (clan, funds, verification, etc)
- Elo returns undefined
- And lastly lastPlayedClass.name doesn't return true (unless I'm calling it incorrectly which is a big possibility, in that case, pls tell me how to call it)

![Screen Shot 2020-03-19 at 11 56 02 AM](https://user-images.githubusercontent.com/61253269/77093380-e1c72a80-69d8-11ea-9a3a-c57c6afe1ee3.png)

**Comment by 1s3k3b** [comment]
what version are you on? (you can check using `npm ls krunker.io.js`) if you are on 1.3.0 or above, can you try reinstalling? otherwise, please update, melees, kr, and elo were added in 1.3.0 if I'm not wrong. social seems to work for me, it's probably fixed by reinstalling/updating. I'll look into the `lastPlayedClass.name` issue.

**Comment by 1s3k3b** [comment]
everything seems to be working for me, and I just realized, math is all good for me as well. calculations were changed in 1.3.0, so you must be on an older version. I won't close this issue for now, let me know if updating fixed it.

**Comment by Xyrrm** [comment]
Oh, my bad updated in wrong folder. Anyway, everything works except elo for 1v1's

**Comment by 1s3k3b** [comment]
it seems that headshots and elos can be undefined in the payload recieved from the API, nothing I can do about it, sadly.

**Comment by Jytesh** [comment]
To fix that you can do (elo)?elo:0

**Comment by Xyrrm** [comment]
Its fine it returns zero not undefined its just that my 1v1 elo isnt 0

**Comment by 1s3k3b** [comment]
right but that's misleading in my opinion, it's not the actual elo, I'd rather have it as `null`.
(also, `x ? x : y` can be simplified to `x || y`)

**Comment by 1s3k3b** [comment]
I just realized elo1 being undefined is an issue with the library too, it's recieved as `elo`, not `elo1` from websockets. gonna fix that in a release today, keeping the issue open until then.

**Comment by 1s3k3b** [comment]
published v1.3.7, please update
