### ISSUE TITLE
fetchClan doesn't work??...anymore

### ISSUE THREAD

**Issue by Xyrrm** [1s3k3b/krunker.io.js#19]
Before only clans with foreign characters caused an error but now every clan I fetch returns "Krunker API Error: Clan not found"

**Comment by Jytesh** [comment]
It is a prob with the server-side, can't do anything but retry.

**Comment by Xyrrm** [comment]
Yeah I've tried many times with many different clans but nothing :(

**Comment by 1s3k3b** [comment]
yes, the Krunker API is generally very unstable, if you get an error which you usually don't, it's likely just the API being unstable. nothing I can do about it, sadly.
