### ISSUE TITLE
Scraping

### ISSUE THREAD

**Issue by Helixable** [1s3k3b/krunker.io.js#2]
Instead of using Web Sockets, why not try scraping the data from the site?

**Comment by 1s3k3b** [comment]
Not sure what you mean 🤔

**Comment by Helixable** [comment]
Web scraping. You know how you can view player stats here: https://krunker.io/social.html
Just do a GET request and parse the data. It's much simpler.

**Comment by 1s3k3b** [comment]
I'm not sure what headers I should use, and I'm not even sure if it supports GET requests. I'm using sockets because I saw them in a bot's source code and later, when I published and realized there were more Krunker packages and looked at source codes, I realized everyone used sockets, I think for a reason.

**Comment by Helixable** [comment]
It supports GET requests. I don't think any special headers are necessary. But in my opinion, Scraping is easier. Whatever suits your project best :)

**Comment by Jytesh** [comment]
> It supports GET requests. I don't think any special headers are necessary. But in my opinion, Scraping is easier. Whatever suits your project best :)

Maybe if you can get that json, send your code, ill make options for the Client so that it can decide to use sockets are change it to social.html scrape.

**Comment by 1s3k3b** [comment]
to be honest, I prefer WebSockets over GET requests, and I don't know what query params I should use for scraping. I don't want to rewrite a good part of the library, and if I would want to, I still wouldn't know necessary data.
