### ISSUE TITLE
Krunker Devs really gotta do us like that

### ISSUE THREAD

**Issue by Xyrrm** [1s3k3b/krunker.io.js#20]
You prob already know the most recent Krunker update completely fucked all krunker bots

**Comment by 1s3k3b** [comment]
I'm aware, I'm gonna publish a fix today, change the WS url to wss://social.krunker.io/ws in your node_modules/krunker.io.js/src/client/Client.js file for a temporary fix

**Comment by Xyrrm** [comment]
Awesome! Ill just wait for the updated release. U doin gods work out here. nice.

**Comment by TheDrone7** [comment]
I was just about to make the same issue myself. Keep up the good work btw.

**Comment by Xyrrm** [comment]
Updated: Still fricked
![Screen Shot 2020-03-27 at 5 35 01 PM](https://user-images.githubusercontent.com/61253269/77806017-77099500-7051-11ea-9f58-d542a8ad4e52.png)
oof

**Comment by Jytesh** [comment]
#21 Should have fixed it.Let me know if it doesn't work.
#Close

**Comment by 1s3k3b** [comment]
1.4.9 was just released which fixed players, leaderboards, and clans.
