### ISSUE TITLE
ELO Image for 0 elo is rank 2

### ISSUE THREAD

**Issue by Xyrrm** [1s3k3b/krunker.io.js#23]
![Screen Shot 2020-04-02 at 11 38 23 AM](https://user-images.githubusercontent.com/61253269/78275008-aba8a100-74d6-11ea-8837-8f1b1ec32400.png)

**Comment by Xyrrm** [comment]
Maybe change "https://krunker.io/img/ranks/icon_${Math.floor(Math.abs(user.stats.elo1 - 120) / 120)}.png" to "https://krunker.io/img/ranks/icon_${Math.floor(Math.abs(user.stats.elo1 - 119) / 120)}.png" so 0 elo doesnt equate to 1 (0-120 = |-120| = 120 / 120 = 1) which is why it displays rank 2 for 0 elo

**Comment by Xyrrm** [comment]
It would reduce each elo rank by one but at least it would display 0 elo correctly

**Comment by 1s3k3b** [comment]
I'll fix it in today's release, thanks for letting me know!
