### ISSUE TITLE
The fetchPlayer method doesn't work

### ISSUE THREAD

**Issue by LeTomium** [1s3k3b/krunker.io.js#48]
I want to create a discord bot. i want to use your package to add some krunker features. But I have a problem:
```js
const krunker = require("krunker.io.js")
const client = new krunker.Client()

client.fetchPlayer(playerName)
    .then(console.log)
    .catch(console.error)
```
Here `playerName` is a string containing a player name. I tried to replace this by `"1s3k3b"` or my own player name that make the same error: `Error: Player not found`. Some help ?

**Comment by 1s3k3b** [comment]
unfortunately, the krunker websockets require captcha verification now, which isn't possible through the lib. you can ask around in the community for a bypass, but I don't want to make it public.
